CREATE TABLE [dbo].[tblPricingModel](
	[idPricingModel] [int] IDENTITY(1,1) NOT NULL,
	[pricingModel] [varchar](max) NULL,
 CONSTRAINT [PK_tblPricingModel] PRIMARY KEY CLUSTERED 
(
	[idPricingModel] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


