CREATE TABLE [dbo].[tblOptionType](
	[idOptionType] [int] IDENTITY(1,1) NOT NULL,
	[OptionType] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_tblOptionType] PRIMARY KEY CLUSTERED 
(
	[idOptionType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


